name: barco_event_master
description: A library for controlling Barco Event Master systems via JSON RPC
version: 3.0.0
homepage: https://github.com/point-source/barco_event_master

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  collection: ^1.16.0
  dart_mappable: ^2.0.0-dev.6
  http: ^0.13.4
  socket_io_client: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.2
  dart_code_metrics: ^5.1.0
  dart_mappable_builder: ^2.0.0-dev.6
  lints: ^2.0.0
  test: ^1.16.0
