name: barco_event_master
description: A library for controlling Barco Event Master systems via JSON RPC
version: 5.0.1
homepage: https://github.com/point-source/barco_event_master

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.16.0
  dart_mappable: ^4.1.0
  http: ^1.1.2
  socket_io_client: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.2
  dart_mappable_builder: ^4.1.0
  lints: ^3.0.0
  test: ^1.16.0
