name: barco_event_master
description: A library for controlling Barco Event Master systems via JSON RPC
version: 2.1.0
homepage: https://github.com/point-source/barco_event_master

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  collection: ^1.16.0
  http: ^0.13.4

dev_dependencies:
  dart_code_metrics: ^4.15.2
  lints: ^2.0.0
  test: ^1.16.0
